version: "3.5"
services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'hasura/smooth-secrets']
    volumes:
      - .:/plugin:ro
  tests:
    image: buildkite/plugin-tester
    volumes:
      - .:/plugin:ro